[package]
name = "wanderlust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "wanderlust"

[lib]
name = "wanderlust"

[[bin]]
name = "testgen"
path = "tests/testgen.rs"
target = 'cfg(test)'
